- Source/CSharpForUE/CSManager.h
- Source/CSharpForUE/Export/UKismetSystemLibraryExporter.cpp
- Source/CSharpForUE/TypeGenerator/CSClass.cpp
- Source/GlueGenerator/CSharpGeneratorUtilities.cpp
- Source/GlueGenerator/GlueGenerator.Build.cs
- Fixed editor freezing on non-param functions
- Exposed DeveloperSettings and BlueprintFunctionLibrary to C#
- Fixed so you can see print strings
- Upgraded to .NET 8.0.1
> Hotfix for UnrealSharp

- Source/GlueGenerator/CSGenerator.cpp
Some fixes to allow UnrealSharp to be an Engine or Project plugin - if it's a project plugin all the generation happens in the normal generation directory.
> Allow install as Engine or Project plugin

- Managed/UnrealSharp/UnrealSharp/Marshallers.cs
- Managed/UnrealSharpPrograms/UnrealSharpWeaver/MetaData/PropertyMetaData.cs
- Source/CSharpForUE/CSManager.cpp
- Source/CSharpForUE/TypeGenerator/CSClass.h
- Source/CSharpForUE/TypeGenerator/Register/CSGeneratedClassBuilder.cpp
- Multiplayer fully supported.
- Event tick now works in pure C# classes
> Added multiplayer and fixed bugs.

- Source/CSharpForUE/TypeGenerator/Register/CSGeneratedClassBuilder.cpp
fix duplicate root components in blueprint editor
> fix duplicate root components

- Managed/UnrealSharpPrograms/UnrealSharpWeaver/MetaData/FunctionMetaData.cs
- Managed/UnrealSharpPrograms/UnrealSharpWeaver/MetaData/PropertyMetaData.cs
- Managed/UnrealSharpPrograms/UnrealSharpWeaver/NativeTypes/NativeDataArrayType.cs
- Managed/UnrealSharpPrograms/UnrealSharpWeaver/NativeTypes/NativeDataStringType.cs
- Managed/UnrealSharpPrograms/UnrealSharpWeaver/NativeTypes/NativeDataType.cs
- Managed/UnrealSharpPrograms/UnrealSharpWeaver/TypeProcessors/FunctionProcessor.cs
- Managed/UnrealSharpPrograms/UnrealSharpWeaver/TypeProcessors/UnrealDelegateProcessor.cs
- Source/CSharpForUE/TypeGenerator/Factories/CSPropertyFactory.cpp
- Source/CSharpForUE/TypeGenerator/Register/CSMetaData.h
Arrays were currently broken due to a bunch of IL issues, this fixes a bunch of IL order mistakes as well as other some other stuff. Also makes them play nice with blueprints as well. Wasn't happy with where i put the check for ParameterType modifier but it seemed to align better with the current code, maybe could have the NativeDataType somehow access to override flags.
> Fixes issues with arrays in delegates, events and rpcs

- Managed/UnrealSharp/UnrealSharp/UnrealSynchronizationContext.cs
Some useful helper methods for async.
Instead of
```[UFunction(FunctionFlags.BlueprintCallable), UMetaData("DisplayName", "Slow Add (Async)")]
public async Task<int> SlowAdd(int lhs, int rhs, CancellationToken cancellationToken)
{
SynchronizationContext.SetSynchronizationContext(UnrealSynchronizationContext.GetContext(NamedThread.GameThread));
PrintString($"Commencing the world's slowest addition...");
await Task.Delay(1000, cancellationToken);
if (cancellationToken.IsCancellationRequested || IsDestroyed) { return default; }
int result = lhs + rhs;
PrintString($"{lhs} + {rhs} = {result}!");
return result;
}
```
Can now just simply do
```[UFunction(FunctionFlags.BlueprintCallable), UMetaData("DisplayName", "Slow Add (Async)")]
public async Task<int> SlowAdd(int lhs, int rhs, …
```
> Added helper methods to Tasks for async context

- Source/CSharpForUE/TypeGenerator/Register/CSGeneratedClassBuilder.cpp
Change was made that caused C# blueprint context items to not show up this fixes that.
> Fixed missing C# blueprint context items.

- Source/UnrealSharpScriptGenerator/Exporters/FunctionExporter.cs
- Source/UnrealSharpScriptGenerator/Utilities/NameMapper.cs
- Source/UnrealSharpScriptGenerator/Utilities/ScriptGeneratorUtilities.cs
Fixed duplicate function declarations
Parameters having same names
> Generator bug fixes

- Managed/UnrealSharp/UnrealSharp/Text.cs
- Managed/UnrealSharpPrograms/UnrealSharpWeaver/NativeTypes/NativeDataTextType.cs
- Source/UnrealSharpEditor/UnrealSharpEditor.cpp
- Source/UnrealSharpScriptGenerator/CSharpExporter.cs
- Source/UnrealSharpScriptGenerator/Exporters/DelegateExporter.cs
- Source/UnrealSharpScriptGenerator/Exporters/FunctionExporter.cs
- Source/UnrealSharpScriptGenerator/Exporters/StructExporter.cs
- Source/UnrealSharpScriptGenerator/Program.cs
- Source/UnrealSharpScriptGenerator/PropertyTranslators/MulticastDelegatePropertyTranslator.cs
- Source/UnrealSharpScriptGenerator/PropertyTranslators/PropertyTranslator.cs
- Source/UnrealSharpScriptGenerator/PropertyTranslators/SinglecastDelegatePropertyTranslator.cs
- Source/UnrealSharpScriptGenerator/PropertyUsage.cs
- Source/UnrealSharpScriptGenerator/Utilities/DotNetUtilities.cs
- Source/UnrealSharpScriptGenerator/Utilities/FileExporter.cs
- Source/UnrealSharpScriptGenerator/Utilities/ScriptGeneratorUtilities.cs
- Source/UnrealSharpScriptGenerator/Utilities/StructUtilities.cs
Fixed marshalling of structs not generating properly
Exporting delegates is now multithreaded aswell
Better debug messages when generating glue
> Glue generator bug fixes

- CSharpForUE.uplugin
- Managed/UnrealSharp/UnrealSharp.Plugins/UnrealSharp.Plugins.csproj
- Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/GenerateProject.cs
- Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Program.cs
- Source/CSharpForUE/CSAssembly.h
- Source/CSharpForUE/CSManagedCallbacksCache.h
- Source/CSharpForUE/CSManager.cpp
- Source/CSharpForUE/CSManager.h
- Source/CSharpForUE/CSharpForUE.Build.cs
- Source/CSharpForUE/CSharpForUE.cpp
- Source/CSharpForUE/Export/FunctionsExporter.h
- Source/UnrealSharpProcHelper/CSProcHelper.cpp
- Source/UnrealSharpScriptGenerator/Utilities/DotNetUtilities.cs
UE Version: 5.4.3
Mac Version: macOS 15.0 Beta(24A5298h)
Dotnet Version: dotnet 8.0.303
Apple M2 Ultra(arm64)
> Mac support.

- Managed/UnrealSharp/UnrealSharp.Plugins/Main.cs
- Managed/UnrealSharp/UnrealSharp/Extensions/CoreUObject/Object.cs
- Managed/UnrealSharp/UnrealSharp/Extensions/CoreUObject/Quat.cs
- Managed/UnrealSharp/UnrealSharp/Extensions/CoreUObject/Rotator.cs
- Managed/UnrealSharp/UnrealSharp/Extensions/CoreUObject/Transform.cs
- Managed/UnrealSharp/UnrealSharp/Interop/FQuatExporter.cs
- Managed/UnrealSharp/UnrealSharp/Interop/FRotatorExporter.cs
- Managed/UnrealSharp/UnrealSharp/Interop/UObjectExporter.cs
- Source/CSharpForUE/CSManagedCallbacksCache.h
- Source/CSharpForUE/CSManager.cpp
- Source/CSharpForUE/CSManager.h
- Source/CSharpForUE/Export/FQuatExporter.cpp
- Source/CSharpForUE/Export/FQuatExporter.h
- Source/CSharpForUE/Export/FRotatorExporter.cpp
- Source/CSharpForUE/Export/FRotatorExporter.h
- Source/CSharpForUE/Export/UObjectExporter.cpp
- Source/CSharpForUE/Export/UObjectExporter.h
- Source/CSharpForUE/TypeGenerator/CSClass.cpp
- Source/CSharpForUE/TypeGenerator/CSClass.h
- Source/CSharpForUE/TypeGenerator/Factories/CSPropertyFactory.cpp
- Source/CSharpForUE/TypeGenerator/Register/CSTypeRegistry.cpp
- Source/UnrealSharpProcHelper/CSProcHelper.cpp
- Source/UnrealSharpProcHelper/CSProcHelper.h
- Source/UnrealSharpScriptGenerator/PropertyTranslators/PropertyTranslatorManager.cs
Fixed FTransform
Added weakptr to core api assembly
Changed names of FTransform members
Fixed compiler warnings
Added new ctor FQuat
> Stability fixes

- Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/GenerateProject.cs
LaunchSettings.json was not being added to the csproj folder. This fixes that.
> Fix launchsettings.json not being added to the csproj

- Managed/UnrealSharp/UnrealSharp.Plugins/Main.cs
- Managed/UnrealSharp/UnrealSharp/Interop/UnmanagedCallbacks.cs
- Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/BuildSolution.cs
- Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/BuildToolAction.cs
- Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/GenerateProject.cs
- Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/PackageProject.cs
- Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/WeaveProject.cs
- Managed/UnrealSharpPrograms/UnrealSharpBuildTool/BuildToolOptions.cs
- Managed/UnrealSharpPrograms/UnrealSharpBuildTool/BuildToolProcess.cs
- Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Program.cs
- Managed/UnrealSharpPrograms/UnrealSharpWeaver/Program.cs
- Source/CSharpForUE/CSManager.cpp
- Source/CSharpForUE/CSManager.h
- Source/CSharpForUE/Export/AActorExporter.cpp
- Source/CSharpForUE/Export/AActorExporter.h
- Source/CSharpForUE/TypeGenerator/Register/CSTypeRegistry.cpp
- Source/UnrealSharpEditor/CSCommands.cpp
- Source/UnrealSharpEditor/CSCommands.h
- Source/UnrealSharpEditor/Slate/CSNewProjectWizard.cpp
- Source/UnrealSharpEditor/UnrealSharpEditor.Build.cs
- Source/UnrealSharpEditor/UnrealSharpEditor.cpp
- Source/UnrealSharpEditor/UnrealSharpEditor.h
- Source/UnrealSharpProcHelper/CSProcHelper.cpp
- Source/UnrealSharpProcHelper/CSProcHelper.h
- Source/UnrealSharpScriptGenerator/Program.cs
- Source/UnrealSharpScriptGenerator/Utilities/DotNetUtilities.cs
- Source/UnrealSharpScriptGenerator/Utilities/FileExporter.cs
- Source/UnrealSharpUtilities/UnrealSharpStatics.cpp
- Source/UnrealSharpUtilities/UnrealSharpStatics.h
All generated code that is related to your project is in its own csproj under /Script/ProjectGlue.
Added button to package c# in editor
> New glue workflow / Button to package C# in the editor

- Source/CSharpForUE/CSharpForUE.cpp
- Source/UnrealSharpEditor/UnrealSharpEditor.cpp
Reverted recent pr i made which has been causing issues with packaged game, needs futherer investigation as to why this happens.
> Revert startup cooking due to packaged game issues

- Source/CSharpForUE/TypeGenerator/Register/CSGeneratedStructBuilder.cpp
Fixed UStruct may mismatch cause Guid
In Unreal Engine 5.4.4
> Fixed UStruct may mismatch cause Guid changed

- Managed/UnrealSharp/UnrealSharp/Extensions/EnhancedInput/ETriggerEvent.cs
- Source/UnrealSharpScriptGenerator/PropertyTranslators/PropertyTranslatorManager.cs
Fixed issue where ETriggerEvent is not having the correct values due to it being a flag and lacking proper uht support, this pr fixes #239.
> Fixed issue with ETriggerEvent not used as flags

- Managed/UnrealSharp/UnrealSharp/Interop/FPropertyExporter.cs
- Managed/UnrealSharp/UnrealSharp/Marshallers.cs
- Source/UnrealSharpCore/Export/FPropertyExporter.cpp
- Source/UnrealSharpCore/Export/FPropertyExporter.h
- Source/UnrealSharpScriptGenerator/PropertyTranslators/BoolPropertyTranslator.cs
https://github.com/UnrealSharp/UnrealSharp/issues/247
> Bool bitfield marshaller #247

- Managed/UnrealSharp/UnrealSharp.ExtensionSourceGenerators/ClassExtenderGenerator.cs
- Managed/UnrealSharp/UnrealSharp.SourceGenerators/AsyncWrapperGenerator.cs
- Managed/UnrealSharp/UnrealSharp.SourceGenerators/DelegateGenerator/DelegateWrapperGenerator.cs
- Managed/UnrealSharp/UnrealSharp.SourceGenerators/NativeCallbacksWrapperGenerator.cs
-add nullable to generated code files to suppress warnings for user
> Suppress nullable warnings for generated user code

- Managed/UnrealSharp/UnrealSharp/SubclassOf.cs
Allow creation of a TSubclassOf with a UClass
> Added TSubclassOf Constructor with UClass

- Managed/UnrealSharp/UnrealSharp.SourceGenerators/AnalyzerStatics.cs
- Managed/UnrealSharp/UnrealSharp.SourceGenerators/CodeAnalyzers/DefaultComponentAnalyzer.cs
- Managed/UnrealSharp/UnrealSharp.SourceGenerators/CodeAnalyzers/UObjectCreationAnalyzer.cs
- Managed/UnrealSharp/UnrealSharp.SourceGenerators/CodeAnalyzers/UnrealTypeAnalyzer.cs
- Managed/UnrealSharp/UnrealSharp.SourceGenerators/CodeSuppressors/DefaultComponentSuppressor.cs
- Managed/UnrealSharp/UnrealSharp.SourceGenerators/RuleCategory.cs
- Source/UnrealSharpScriptGenerator/UnrealSharpScriptGenerator.ubtplugin.csproj.props
Added new analyzers:
1. UObject new keyword creation
2. DefaultComponent on not UActorComponent types
3. DefaultComponent Property without setter
> U# additional analyzers

- Source/UnrealSharpCore/TypeGenerator/CSScriptStruct.h
> UE 5.5 Fix building project error

- Source/UnrealSharpEditor/Reinstancing/CSReinstancer.cpp
> -fix reinstancing macro nodes with wildcards

- Managed/UnrealSharp/UnrealSharp.ExtensionSourceGenerators/ActorExtensionGenerator.cs
simple fix for the extension source generator
> -fix invalid code generation for changed api

- Managed/UnrealSharp/UnrealSharp/Extensions/Actor.cs
- Source/UnrealSharpCore/Extensions/Libraries/CSWorldExtensions.cpp
- Source/UnrealSharpCore/Extensions/Libraries/CSWorldExtensions.h
This issue exposes FinishSpawning on actors to allow to deferred actor spawning.
> Exposes FinishSpawning on actor

- Managed/UnrealSharp/UnrealSharp/Extensions/CoreUObject/Object.cs
- Managed/UnrealSharp/UnrealSharp/Extensions/Engine/DataTable.cs
- Managed/UnrealSharp/UnrealSharp/Interop/FNameExporter.cs
- Managed/UnrealSharp/UnrealSharp/Interop/UObjectExporter.cs
- Managed/UnrealSharp/UnrealSharp/Name.cs
- Managed/UnrealSharp/UnrealSharp/SubclassOf.cs
- Managed/UnrealSharp/UnrealSharp/UnrealSharp.csproj
- Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/PackageProject.cs
- Source/UnrealSharpCore/Export/FNameExporter.cpp
- Source/UnrealSharpCore/Export/FNameExporter.h
- Source/UnrealSharpCore/Export/UObjectExporter.cpp
- Source/UnrealSharpCore/Export/UObjectExporter.h
- Source/UnrealSharpCore/Extensions/Libraries/CSDataTableExtensions.cpp
- Source/UnrealSharpCore/Extensions/Libraries/CSDataTableExtensions.h
This issue is a quick fix for FName during packaged builds mainly for the new logging system.
> Fixes FName data alignment

- Managed/UnrealSharp/UnrealSharp.SourceGenerators/AnalyzerStatics.cs
- Managed/UnrealSharp/UnrealSharp.SourceGenerators/CodeAnalyzers/UInterfaceAnalyzer.cs
https://github.com/UnrealSharp/UnrealSharp/pull/325/commits/4133bf2ef5fb5e9674c8466f953ac4fc4263f3f4
Added 2 analyzer for UInterface attribute: 
1. UProperty with interface type
2. UFunction with interface parameter type
> UInterface analyzer

- Source/UnrealSharpCore/Export/AsyncExporter.cpp
- Source/UnrealSharpCore/TypeGenerator/Functions/CSFunction.cpp
This issue fixes some edge case issues with world context for now by removing the nullptr of the current context.
> Fixes world context issues

- Source/UnrealSharpCore/CSManager.h
This issue fixes some gc issues with WorldContext by changing it to a WeakPtr.
Fixes #332
> Fixes World Context GC Issues

- Source/UnrealSharpScriptGenerator/Utilities/FunctionUtilities.cs
- Source/UnrealSharpScriptGenerator/Utilities/ScriptGeneratorUtilities.cs
This pr fixes autocast from exporting functions if they don't pass the autocast checks.
> Fixes autocast from causing some methods to be ignored.

- Managed/UnrealSharp/UnrealSharp/Extensions/CoreUObject/Object.cs
- Managed/UnrealSharp/UnrealSharp/Interop/UObjectExporter.cs
- Source/UnrealSharpCore/Export/UObjectExporter.cpp
- Source/UnrealSharpCore/Export/UObjectExporter.h
This pr adds the property UniqueID to the UObject type
> Added UniqueID to UObjects

- Managed/UnrealSharp/UnrealSharp/Extensions/CoreUObject/Guid.cs
This pr allows for conversion between Unreal and .Net Guid conversion as well as some basic equality features.
> Extended FGuid to allow for .net Guid conversion

- Managed/UnrealSharp/UnrealSharp/Extensions/CoreUObject/PackageName.cs
- Source/UnrealSharpCore/Extensions/Libraries/CSPackageNameExtensions.cpp
- Source/UnrealSharpCore/Extensions/Libraries/CSPackageNameExtensions.h
This pr exposes some useful methods in FPackageName used for user generated content loading.
> Exposes FPackageName

- Managed/UnrealSharp/UnrealSharp/Extensions/Engine/World.cs
- Source/UnrealSharpCore/Extensions/Libraries/CSWorldExtensions.cpp
- Source/UnrealSharpCore/Extensions/Libraries/CSWorldExtensions.h
This PR exposes the World URL property allowing you to get the FURL of the world  mimicking on World->URL
> Exposes URL property on world to C#

- Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/WeaveProject.cs
- Managed/UnrealSharpPrograms/UnrealSharpWeaver/Program.cs
Related issues https://github.com/UnrealSharp/UnrealSharp/issues/371
> Remove stripping of ProjectGlue in WeaveProject

- Managed/UnrealSharp/UnrealSharp/Extensions/CoreUObject/Object.cs
- Managed/UnrealSharp/UnrealSharp/Interop/UKismetSystemLibraryExporter.cs
- Source/UnrealSharpCore/Export/UKismetSystemLibraryExporter.cpp
- Source/UnrealSharpCore/Export/UKismetSystemLibraryExporter.h
Adds the key parameter to PrintString to have feature parity with the BP/CPP version
> Added optional Key parameter to PrintString

- Managed/UnrealSharp/UnrealSharp/Extensions/Engine/Actor.cs
This function uses a generic for the return value and takes in a TSubclassOf. This is in cases where you have a base class you want to return as, but want to create a specific subclass using a TSubclassOf
> Add new AddComponentByClass function

- Source/UnrealSharpCore/Extensions/Subsystems/CSEngineSubsystem.h
- Source/UnrealSharpCore/Extensions/Subsystems/CSGameInstanceSubsystem.h
- Source/UnrealSharpCore/Extensions/Subsystems/CSLocalPlayerSubsystem.h
This PR adds a conditional FTickableGameObject to Subsystems, which ticking can be enabled with the UProperty IsTickable.
> Added Optional Tickable Subsystem

- Source/UnrealSharpBinds/Private/CSBindsManager.cpp
- Source/UnrealSharpBinds/Public/CSBindsManager.h
- Source/UnrealSharpCore/Extensions/Libraries/CSActorExtensions.cpp
- Source/UnrealSharpCore/TypeGenerator/Register/CSSimpleConstructionScriptBuilder.h
- Source/UnrealSharpEditor/AssetActions/CSAssetTypeAction_CSBlueprint.cpp
- Source/UnrealSharpEditor/AssetActions/CSAssetTypeAction_CSBlueprint.h
- Source/UnrealSharpEditor/UnrealSharpEditor.h
- Source/UnrealSharpManagedGlue/Exporters/NativeBindExporter.cs
1 fix compile error on mac
2 fix marshalling on mac
> 1 fix compile error on mac

- Managed/UnrealSharp/UnrealSharp.Core/Marshallers/BlittableMarshaller.cs
- Managed/UnrealSharp/UnrealSharp/Extensions/CoreUObject/Vector.cs
- Managed/UnrealSharp/UnrealSharp/Extensions/CoreUObject/Vector2D.cs
- Managed/UnrealSharp/UnrealSharp/Extensions/Engine/Actor.cs
- Managed/UnrealSharpPrograms/UnrealSharpWeaver/MetaData/ClassMetaData.cs
- Managed/UnrealSharpPrograms/UnrealSharpWeaver/MetaData/FunctionMetaData.cs
- Managed/UnrealSharpPrograms/UnrealSharpWeaver/TypeProcessors/FunctionProcessor.cs
- Managed/UnrealSharpPrograms/UnrealSharpWeaver/TypeProcessors/UnrealClassProcessor.cs
- Managed/UnrealSharpPrograms/UnrealSharpWeaver/TypeProcessors/UnrealDelegateProcessor.cs
- Managed/UnrealSharpPrograms/UnrealSharpWeaver/Utilities/MethodUtilities.cs
- Source/UnrealSharpCompiler/CSCompilerContext.cpp
- Source/UnrealSharpCore/CSAssembly.cpp
- Source/UnrealSharpCore/CSManagedMethod.cpp
- Source/UnrealSharpCore/CSManager.cpp
- Source/UnrealSharpCore/CSManager.h
- Source/UnrealSharpCore/Export/UObjectExporter.cpp
- Source/UnrealSharpCore/TypeGenerator/Functions/CSFunction.cpp
- Source/UnrealSharpCore/TypeGenerator/Functions/CSFunction_NoParams.cpp
- Source/UnrealSharpCore/TypeGenerator/Functions/CSFunction_Params.cpp
- Source/UnrealSharpCore/TypeGenerator/Register/CSGeneratedClassBuilder.cpp
- Source/UnrealSharpCore/TypeGenerator/Register/CSGeneratedClassBuilder.h
- Source/UnrealSharpManagedGlue/Exporters/FunctionExporter.cs
- Source/UnrealSharpManagedGlue/GeneratorStringBuilder.cs
- Source/UnrealSharpManagedGlue/PropertyTranslators/BlittableCustomStructTypePropertyTranslator.cs
- Source/UnrealSharpManagedGlue/PropertyTranslators/PropertyTranslator.cs
- Source/UnrealSharpManagedGlue/PropertyTranslators/PropertyTranslatorManager.cs
- Source/UnrealSharpManagedGlue/PropertyTranslators/StructPropertyTranslator.cs
Fixed delegates emitting invalid IL in shipping configuration, optimizations to getting managed object from c++, faster calls to c++ from C# on blittable parameters
> General fixes

- Source/UnrealSharpManagedGlue/UnrealSharpManagedGlue.ubtplugin.csproj
Added unreal engine define constant inheritance on build.
> unreal engine define constant inheritance on build

- Managed/UnrealSharp/UnrealSharp/Extensions/CoreUObject/Transform.cs
Fixes #543 provided by @thomasfn
> Added inverse transform math to FTransform

- Managed/UnrealSharp/UnrealSharp/Extensions/CoreUObject/Object.cs
- Managed/UnrealSharp/UnrealSharp/Interop/UObjectExporter.cs
- Source/UnrealSharpCore/Export/UObjectExporter.cpp
- Source/UnrealSharpCore/Export/UObjectExporter.h
Introduces StaticLoadClass and StaticLoadObject methods to UObject and exposes corresponding interop and native functions. These allow loading classes and objects by asset path, improving dynamic asset management capabilities.
> Add static load methods for classes and objects
