UnrealSharp/UnrealSharp

Managed/UnrealSharp/UnrealSharp/SubclassOf.cs
Source/GlueGenerator/CSGenerator.cpp
Source/GlueGenerator/CSGenerator.h
Source/GlueGenerator/CSModule.cpp
Source/GlueGenerator/CSNameMapper.cpp
Source/GlueGenerator/CSScriptBuilder.cpp
Source/GlueGenerator/CSScriptBuilder.h
Source/GlueGenerator/CSharpGeneratorUtilities.cpp

Fixing T reuse warnings
If the namespace has a - in it, replace with _
If the field name has a - or a space, remove them.
Improvements to the string concatenation to use string builder.
Fixing how modules are assigned a directory so that game plugins are associated with the game module assembly generation folder.
Fixing a possibility uninitiated variable the compiler warned about. 'uppercaseCount'
Simplified how you lookup a module from a UObject*, all the calls were really FindOrRegisterModule, so that's what they are, and we pass in the Uobject* as directly as possible to not lose valuable context we need to possibly lookup to find the module correctly.

General fixes

---

Source/CSharpForUE/CSDeveloperSettings.h
Source/UnrealSharpEditor/UnrealSharpEditor.cpp
Source/UnrealSharpEditor/UnrealSharpEditor.h

I tend to hit CTRL + S very frequently when I'm typing code, so I added a small toggle to hold off on Hot Reloading until Unreal Engine regains focus

Add a setting to require editor focus for Hot Reload

---

Managed/UnrealSharp/UnrealSharp/Attributes/UFunctionAttribute.cs
Managed/UnrealSharp/UnrealSharp/Attributes/UPropertyAttribute.cs
Managed/UnrealSharp/UnrealSharp/NativePropertyFlags.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/MetaData/BaseMetaData.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/MetaData/FunctionMetaData.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/MetaData/PropertyMetaData.cs
Source/CSharpForUE/TypeGenerator/Factories/CSFunctionFactory.cpp
Source/CSharpForUE/TypeGenerator/Factories/CSFunctionFactory.h

First commit fixes an issue where metadatas weren't being applied when used in UFunctions: 
```csharp
// This works correctly
[UProperty(PropertyFlags.EditAnywhere | PropertyFlags.BlueprintReadWrite), UMetaData("DisplayName","MyInteger"), UMetaData("Category","Inner|TestCat")]
public int TestInt { get; set; }
// Both UMetaData weren't being applied
[UFunction(FunctionFlags.BlueprintCallable), UMetaData("DisplayName", "MyTestFunction"), UMetaData("Category","Inner|TestCat")]
public void TestFunction()
{
}
```
Second commit makes some PropertyFlags work closer to how they work in C++ (I haven't tried every combination, but so far, I haven't encountered an issue). Also fixes the following issue where a combination of BlueprintReadWrite and EditAnywhere was causing the property to be ReadOnly …

Fix UFunctions not applying the metadata defined in C# and Fix some PropertyFlags mismatch with how they work C++

---

Managed/UnrealSharp/UnrealSharp/Transform.cs

Unreal's FTransform is encoded as 3 vec4s - a quaternion rotation, translation and scale. Currently the C# counterpart is encoded as 3 vec3s sequential meaning the fields were misaligned. Furthermore the C# has the rotation as a rotator when it's actually a quaternion. This fixes both. The added u0 and u1 fields serve as padding. An alternative if unused fields are undesirable could be to use explicit struct layout instead, happy to change it to this if requested.

Fixed transform fields misalignment with native

---

Managed/UnrealSharp/UnrealSharp/Extensions/Actor.cs
Source/GlueGenerator/CSGenerator.cpp
Source/GlueGenerator/PropertyTranslators/PropertyTranslator.cpp

Currently it's not possible to add components to an actor at runtime. You can get close (via `NewObject` and `AttachToComponent`) but there's no way to call `RegisterComponent` on the component because that is not exposed to BP. Instead, BP gets a custom made node called 'Add Component By Class' so that it could dynamically add pins to support any `ExposeOnSpawn` properties. Internally, this node calls the UFunction `AddComponentByClass` (which is marked blueprint internal) and optionally the UFunction `FinishAddComponent` if there are `ExposeOnSpawn` properties (so that they can be set in between `NewObject` and `RegisterComponent`. There's also a bunch of probably important default object stuff in there I don't understand.
This PR binds the internal `AddComponentByClass` and …

Added AddComponentByClass variants to Actor

---

Source/GlueGenerator/PropertyTranslators/CSSupportedPropertyTranslators.cpp

There are still some BP APIs that use single precision variants of math structs, like `Vector2f/3f/4f` etc. Currently the glue code generates these structs but it'd be better to use `System.Numerics` where possible (the glue code does already use `System.DoubleNumerics` for the usual double precision variants).
Example code:
```C#
PrintString($"Vector3f: {StringLibrary.Conv_Vector3fToString(new System.Numerics.Vector3(1.0f, 2.0f, 3.0f))}");
```

Map single float variants of math structs to System.Numerics

---

Managed/UnrealSharp/UnrealSharp/Interop/FStringExporter.cs
Managed/UnrealSharp/UnrealSharp/Interop/ManagedCallbacks.cs
Managed/UnrealSharp/UnrealSharp/Interop/UnmanagedCallbacks.cs
Managed/UnrealSharp/UnrealSharp/Marshallers.cs
Source/CSharpForUE/CSDeveloperSettings.h
Source/CSharpForUE/CSManagedCallbacksCache.h
Source/CSharpForUE/Export/FStringExporter.cpp
Source/CSharpForUE/Export/FStringExporter.h
Source/CSharpForUE/TypeGenerator/CSClass.cpp
Source/CSharpForUE/TypeGenerator/CSClass.h

Currently exceptions thrown in a C# UFunction are swallowed up and logged to somewhere unuseful. This PR changes the managed method invoke mechanism to allow exceptions to be passed back to C++ and injected into the stack frame, allowing the BP error handler to take over. Most importantly this shows the exception in the output log as it occurs, which makes debugging considerably easier.
Example code:
```C#
[UFunction(FunctionFlags.BlueprintCallable)]
public void TestException()
{
throw new Exception("Test exception!");
}
```
The errors are marked as fatal which seems to end the PIE session immediately - I'm not sure if that's too severe and maybe they should only be warnings instead? Then again exceptions are pretty bad and the user can always wrap their own code in try/catch so maybe …

Added proper handling of exceptions thrown by managed events

---

Managed/UnrealSharpPrograms/UnrealSharpWeaver/WeaverHelper.cs

At some point the `IsBlittableStruct` property probably got renamed to `IsBlittable` and this was forgot to be updated.
Fixes https://github.com/UnrealSharp/UnrealSharp/issues/68 (contains code example for reproduction).

Fixed crash when exporting properties with blittable structs

---

Managed/UnrealSharp/UnrealSharp.SourceGenerators/DelegateGenerator/MulticastDelegateBuilder.cs
Managed/UnrealSharp/UnrealSharp/Extensions/Actor.cs
Managed/UnrealSharp/UnrealSharp/Interop/AActorExporter.cs
Source/CSharpForUE/Export/AActorExporter.cpp
Source/CSharpForUE/Export/AActorExporter.h
Source/GlueGenerator/CSGenerator.cpp
Source/GlueGenerator/CSGenerator.h
Source/GlueGenerator/CSharpGeneratorUtilities.cpp
Source/GlueGenerator/CSharpGeneratorUtilities.h
Source/GlueGenerator/PropertyTranslators/PropertyTranslator.cpp
Source/GlueGenerator/PropertyTranslators/PropertyTranslator.h

This adds glue code generation of public native properties as well as ones exposed to blueprint. This fixes nothing being generated for `FHitResult` (as the members of that struct were not exposed to blueprint, and instead blueprint support was implemented via a native break), and gains a number of other additional bindings.
It did reveal a number of naming conflicts however.
- Fields being named as the same as the enclosing type - fixed by prefixing conflicted members with `K2_`, which was already supposed to be happening but was broken
- Stripping prefixes from properties e.g. types with `bool bOverrideGravity` and `FVector OverrideGravity`, and after stripping the prefix from `bOverrideGravity` this obviously created a conflict with `OverrideGravity`) - fixed by not stripping prefixes …

Fixed FHitResult not being populated

---

Source/CSharpForUE/TypeGenerator/CSClass.cpp
Source/CSharpForUE/TypeGenerator/CSClass.h

The managed invoke code works by allocating a buffer called `ArgumentData` and copying parameters from the execution stack to the buffer. This buffer is then passed along to C#, which marshals the parameters out of the buffer into it's own format. C# uses `FProperty::GetOffset_ForInternal` to determine where in the `ArgumentData` buffer to read from. However, the managed invoker was not considering the property offset at all when preparing the buffer and instead was simply appending to the buffer - making the false assumption that the offset of property 2 would be equal to the offset of property 1 + the size of property 1. This meant that if the properties were ever padded for some reason (most likely to keep things like pointers aligned in memory), the offsets didn't line up and C# ended …

Fixed invoke managed method alignment issue

---

Managed/UnrealSharp/UnrealSharp/Extensions/CoreUObject/PrimaryAssetType.cs

Adds a constructor for PrimaryAssetType that lets you pass an FName to set the Name property, matching the C++ constructor
Without
```
PrimaryAssetType ExperienceList = new()
{
Name = nameof(LyraUserFacingExperienceDefinition)
};
```
With
```
PrimaryAssetType ExperienceList = new(nameof(LyraUserFacingExperienceDefinition));
```

Add name constructor to PrimaryAssetType

---

Managed/UnrealSharp/UnrealSharp/UnrealSharpObject.cs

Small change that makes it so the Getter functions in UnrealSharpObject can now get C++ subsystems as well, not just C# subclasses

Subsystem Getters can now get C++ defined subsystems

---

Source/GlueGenerator/CSGenerator.cpp

Interfaces with methods that have parameters referencing the interface were causing an infinite loop and stack overflow in the glue generator.
Code to reproduce:
```C++
UINTERFACE(BlueprintType)
class UTestCrash : public UInterface
{
GENERATED_BODY()
};
/**
*
*/
class ITestCrash : public IInterface
{
GENERATED_BODY()
public:
UFUNCTION(BlueprintCallable, BlueprintNativeEvent)
void TestCrashFunction(const TScriptInterface<ITestCrash>& Test);
};
```

Fixed self-referencing interfaces causing stack overflow

---

README.md

I noticed that the code snippet in the README was not syntax highlighted, so I went ahead and updated it here. I also cloned the Wiki and updated all of the snippets and code blocks there with the correct language semantics so they would be highlighted, as well as made a few style changes. I cannot find a way to make a PR for a repository's wiki, however, but you can see the changes I made in my [forked repository](https://github.com/not-nugget/UnrealSharp/wiki).

Update README.md code snippet with syntax-highlighting

---

Managed/UnrealSharp/UnrealSharp/Interop/FStringExporter.cs
Managed/UnrealSharp/UnrealSharp/Name.cs
Source/CSharpForUE/Export/FStringExporter.cpp
Source/CSharpForUE/Export/FStringExporter.h

As far as I can tell this is the only case where a string was being leaked. I haven't changed arrays though and it's possible they need similar treatment.

Fixed memory leak when using Name.ToString.

---

Source/CSharpForUE/TypeGenerator/Factories/CSFunctionFactory.cpp

the function must have FUNC_HasOutParms flag with any properties have CPF_OutParm flag

fix InvokeManagedMethod crash.

---

Source/GlueGenerator/CSGenerator.cpp
Source/GlueGenerator/CSGenerator.h
Source/GlueGenerator/PropertyTranslators/DelegateBasePropertyTranslator.cpp
Source/GlueGenerator/PropertyTranslators/SinglecastDelegatePropertyTranslator.cpp

This fixes a few singlecast delegate related issues.
- If the delegate was declared in a different module A, it wasn't getting a using to that module being added to the glue code for a class in module B
- This also goes for if the delegate is declared and used in an interface, both in a different module A, then the interface method using the delegate is overridden in a class in module B
- The marshal from native buffer code was implemented incorrectly. As far as I can tell this code path only happens when implementing an interface, e.g.
```C++
DECLARE_DYNAMIC_DELEGATE(FTestSinglecastWithoutParamsDelegate);
UINTERFACE(MinimalAPI, Blueprintable)
class UTestDelegatesInterface : public UInterface
{
GENERATED_BODY()
};
class ITestDelegatesInterface
{
GENERATED_BODY()
public: …
```

Fix singlecast delegate issues

---

Source/CSharpForUE/CSManager.cpp
Source/CSharpForUE/Export/FGameplayTagExporter.cpp
Source/CSharpForUE/Export/FGameplayTagExporter.h
Source/CSharpForUE/Export/UWorldExporter.cpp
Source/CSharpForUE/Extensions/CSCancellableAsyncAction.cpp
Source/CSharpForUE/TypeGenerator/CSClass.cpp
Source/CSharpForUE/TypeGenerator/Factories/CSFunctionFactory.cpp
Source/CSharpForUE/TypeGenerator/Factories/CSMetaDataFactory.cpp
Source/CSharpForUE/TypeGenerator/Factories/CSPropertyFactory.cpp
Source/CSharpForUE/TypeGenerator/Register/CSMetaData.cpp
Source/CSharpForUE/TypeGenerator/Register/CSMetaData.h
Source/CSharpForUE/TypeGenerator/Register/CSTypeRegistry.cpp
Source/CSharpForUE/TypeGenerator/Register/TypeInfo/CSEnumInfo.h
Source/CSharpForUE/TypeGenerator/Register/TypeInfo/CSInterfaceInfo.h
Source/CSharpForUE/TypeGenerator/Register/TypeInfo/CSStructInfo.h
Source/GlueGenerator/CSGenerator.h
Source/GlueGenerator/CSharpGeneratorUtilities.cpp
Source/UnrealSharpProcHelper/CSProcHelper.cpp

I tried this plugin using Windows 11 and Unreal Engine 5.4. Got a lot of compiling issues. Mostly it was missing includes and forgotten TEXT macros.
I also switch from using `Cast` to `CastField` inside (Source/GlueGenerator/CSharpGeneratorUtilities.cpp:150)
I also changed 'RF_PendingKill' to 'RF_MirroredGarbage' inside (Source/CSharpForUE/Extensions/CSCancellableAsyncAction.cpp:10)
Committed by Robin Johannesson.

Fixed includes, TEXT macros, linking and cast issues

---

Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/BuildSolution.cs
Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/WeaveProject.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/Program.cs

Currently if you use any kind of type in a ufunction or uproperty of such from another project it'll cause a weaver file lock. This fixes that by applying the same resolver the managed UnrealSharp project does before hand.
Let me know if you'd like me to also fix unmanaged dlls in this pr and will also work on that.

Fixes user assembly resolving managed dlls

---

Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/GenerateProject.cs
Source/UnrealSharpScriptGenerator/UnrealSharpScriptGenerator.ubtplugin.csproj

This should fix the error `The imported project "C:\Source\Programs\Shared\UnrealEngine.csproj.props" was not found.`

Fix EngineDir not being set when compiling UnrealSharpScriptGenerator

---

Managed/UnrealSharp/UnrealSharp.Plugins/Main.cs

Modifies the UnrealSharp.Plugins project to expose public functions for loading and unloading assemblies.
Only for advanced usage but very helpful if someone wants to leverage UnrealSharp's dll loading/unloading system.

Expose public LoadPlugin and UnloadPlugin functions

---

Source/CSharpForUE/CSManager.cpp
Source/UnrealSharpScriptGenerator/Program.cs

I noticed that the ManagedProject.csproj file doesn't get generated until you boot up Unreal Engine. This change should generate it at compile time.

Generate ManagedProject.csproj at compile time

---

Managed/UnrealSharpPrograms/UnrealSharpWeaver/Program.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/WeaverHelper.cs

- fix user breakponits not hitting by copying over the metadata tokens of the original method.
- disabling pdb generation since it does not make sense will rewrite all debugging metadata wich prevents from matching code  IL code to user code manually (like with metadata tokens)
this will lead to matching debug symbols for IL method copies and breakpoints will hit like desired for user code.
i made more extensive tests with 
- calling event functions from blueprints
- implementing delegates and callbacks to regular ufunctions and event functions
- general [UFunction(FunctionFlags.BlueprintEvent | FunctionFlags.BlueprintCallable)] decorations

fix #176 -user breakpoints will not hit for user code for unreal event implementations

---

Managed/UnrealSharpPrograms/UnrealSharpWeaver/TypeProcessors/FunctionProcessor.cs

all virtual methods have base methods. change the code to check if the base method is not the current implementation. this base method should always be the root base method as well from the Cecil underlying impl

fix #178 -fix missing IL code for 'virtual' base method after weaving 

---

Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/WeaveProject.cs

Fixes a current issue with path in the BuildTool causing assembly to not be loaded in the assembly resolver

Fixed issue with weaver project paths

---

Source/UnrealSharpEditor/UnrealSharpEditor.cpp

Someone was running into a problem where their other obj/bin folders weren't being ignored with the directory watcher, so now its checks for the folders without the Script prefix to account for subfolders

Fixed obj/bin folders not being ignored in Script subfolders

---

Source/CSharpForUE/CSDeveloperSettings.h

UCSDeveloperSettings now uses EditorPerProjectUserSettings so it shows up within Editor Preferences instead of the Project Settings, since the settings are editor specific.
Prior to this change the settings also did not save locally for me, after moving it over to this config they get saved and persist between editor launches.

Move developer settings to Editor preferences

---

Source/CSharpForUE/CSDeveloperSettings.h
Source/UnrealSharpEditor/UnrealSharpEditor.cpp
Source/UnrealSharpEditor/UnrealSharpEditor.h

- Moved to using an enum for the automatic reload developer setting for multiple states (`OnScriptSave`, `OnEditorFocus`, `Off`).
- Moved to using an enum for `bIsReloading` in `UnrealSharpEditor` for multiple states (`Inactive`, `PendingReload`, `Active`).
- `PendingReload` is a new state that gets set to true when the DirectoryWatcher finds script changes, but the automatic setting is set to only Hot Reload on Focus or Manual.
- `HotReloadStatus` is now set to active and inactive within `StartHotReload()`, so it does not need to be manually set to true and false when calling the function.
- `StartHotReload()` is no longer static so the `HotReloadStatus` can be set within the function.
- There's now static `OnCompileManagedCode()` and `OnOpenSolution()` functions that the commands …

Added setting to disable automatic HotReload

---

Managed/UnrealSharpPrograms/UnrealSharpWeaver/Program.cs

Right now if there are native runtimes or any other files in sub directories in project bin folders they are ignored, this fixes that by copying files over recursively.

Recursive dependency copying

---

Managed/UnrealSharp/UnrealSharp.SourceGenerators/AnalyzerStatics.cs
Managed/UnrealSharp/UnrealSharp.SourceGenerators/DelegateGenerator/DelegateWrapperGenerator.cs
Managed/UnrealSharp/UnrealSharp/Attributes/UMultiDelegateAttribute.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/Program.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/TypeProcessors/UnrealDelegateProcessor.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/WeaverHelper.cs

Any delegates in a project the weaver will attempt to glue even if the user doesn't want to expose a delegate to USharp, this changes that and requires all delegates that the user wants to be glued requires an attribute.
```c#
// Multicast delegates.
[UMultiDelegate]
public delegate void MyShowcaseMulticastDelegate(int a);
// Single delegates.
[USingleDelegate]
public delegate void MyShowcaseDelegate(int a);
```

Changed Delegates glue exposure

---

Source/CSharpForUE/CSharpForUE.cpp
Source/UnrealSharpEditor/UnrealSharpEditor.cpp

Right now when packaging cooking creates a new instance of unreal causing it to call into InitializeUnrealSharp(), this PR fixes this.

Fixed cooking calling into Initialize

---

Managed/UnrealSharpPrograms/UnrealSharpWeaver/TypeProcessors/FunctionProcessor.cs

Implementation methods sometimes rename none base type methods if you are calling a method with the same name, this fixes that.

Fixed Implementation methods renaming none base methods

---

Managed/UnrealSharp/UnrealSharp/Marshallers.cs

Add a guard to the StringMarshaller to guard against C# null strings (treat as string.Empty instead)
Otherwise:
[UProperty(PropertyFlags.BlueprintReadOnly)]
public string TestString { get; set; }
Will crash with an Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000

Guard against C# null strings on [UProperty]

---

Managed/UnrealSharp/UnrealSharp/Extensions/Engine/TimerHandle.cs
Managed/UnrealSharp/UnrealSharp/Extensions/EnhancedInput/InputActionValue.cs
Source/UnrealSharpScriptGenerator/CSharpExporter.cs
Source/UnrealSharpScriptGenerator/Exporters/ClassExporter.cs
Source/UnrealSharpScriptGenerator/Exporters/StructExporter.cs

This PR fixes an issue currently with manually exported types not having the GeneratedType attribute applied to them causing them to become FallBack structs when doing object lookups by name C++ side.

Fixed issue with manually exported types

---

Managed/UnrealSharp/UnrealSharp/Extensions/CoreUObject/Vector2D.cs

this fixes an issue in UnrealSharp.csproj FVector2D.Transform(FVector2D value, FQuat rotation) which had used Quaternion instead of FQuat in arg rotation

-fix usage of Quaternion instead of FQuat

---

Managed/UnrealSharpPrograms/UnrealSharpWeaver/MetaData/PropertyMetaData.cs
Source/UnrealSharpCore/TypeGenerator/Factories/CSPropertyFactory.cpp
Source/UnrealSharpCore/TypeGenerator/Register/MetaData/CSPropertyMetaData.cpp
Source/UnrealSharpCore/TypeGenerator/Register/MetaData/CSPropertyMetaData.h

Removed some changes from #147 that are no longer neccessary and gets rid of a warning that Unreal spams in console when using RPCs with arrays.

Removed now unnecessary array fix

---

Managed/UnrealSharp/UnrealSharp.SourceGenerators/AsyncWrapperGenerator.cs
Managed/UnrealSharp/UnrealSharp.SourceGenerators/DelegateGenerator/DelegateBuilder.cs
Managed/UnrealSharp/UnrealSharp.SourceGenerators/DelegateGenerator/DelegateWrapperGenerator.cs
Managed/UnrealSharp/UnrealSharp.SourceGenerators/NativeCallbacksWrapperGenerator.cs

-Fix AsyncWrapperGenerator and NativeCallbacksWrapperGenerator do not pick up generic type argument namespaces which will lead to failing compilation of generated code
-Fix delegate parameter could not be passed by ref or in or out when used with TDelegate.

Code Generator fixes

---

Source/UnrealSharpBlueprint/K2Node_CSAsyncAction.cpp
Source/UnrealSharpBlueprint/K2Node_CSAsyncAction.h
Source/UnrealSharpBlueprint/K2Node_CSCancellableAsyncAction.h
Source/UnrealSharpEditor/Reinstancing/CSReinstancer.cpp
Source/UnrealSharpEditor/Reinstancing/CSReinstancer.h
Source/UnrealSharpEditor/UnrealSharpEditor.Build.cs

-properly reconstruct methods and async methods on c# recompile reload. this will also now pick up any changes to signatures and prevent blueprints from breaking since they reference their old types.
will fix #238 and #250

-fix #238 #250 reinstancing is not performed on method (UK2Node_CallFunction or UK2Node_CSAsyncAction) nodes.

---

Managed/UnrealSharp/UnrealSharp/Attributes/MetaTags.cs

Suppress 'Parameter is unread' on this file as these parameters are used via reflection
(and add ToolTip as a valid for Properties)

[Minor] MetaTags - Suppress 'Parameter is unread' warnings on this file

---

Source/UnrealSharpCore/CSManager.h

Was getting an error within CSManager stating the raw pointers needed to be converted to TObjectPtr<>

Fixed 5.5 error requiring TObjectPtr

---

Source/UnrealSharpEditor/Reinstancing/CSReinstancer.cpp
Source/UnrealSharpEditor/Reinstancing/CSReinstancer.h
Source/UnrealSharpEditor/UnrealSharpEditor.Build.cs

-replace more remaining data in BPS to update for reinstancing. also unreals api is used to trigger skeleton updates and changed events so recompilation will trigger like it would with c++  class changes.
This is solving the case shown above. Using a BP class not inheriting from c# with a function using a struct from c# in its parameters and the BP will use a variable of type of the c# struct too,

fix #250: BP skeleton updates where not performed on BP's using u# types (i.e. as function parameters or variables)

---

Managed/UnrealSharp/UnrealSharp.Plugins/Main.cs
Managed/UnrealSharp/UnrealSharp.Plugins/PluginLoadContextWrapper.cs
Managed/UnrealSharp/UnrealSharp.Plugins/PluginLoader.cs
Managed/UnrealSharp/UnrealSharp.Plugins/PluginsInfo.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/MetaData/UnrealSharpMetadata.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/NativeTypes/NativeDataSimpleType.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/NativeTypes/NativeDataStringType.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/NativeTypes/NativeDataType.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/Program.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/WeaverHelper.cs
Source/UnrealSharpProcHelper/CSProcHelper.cpp
Source/UnrealSharpProcHelper/CSProcHelper.h
Source/UnrealSharpProcHelper/UnrealSharpProcHelper.Build.cs

Added support for U# project referencing.
Algorithm:
1. UnrealSharpWeaver order all user assembly by U# dependencies.
2. Create file UnrealSharp.metadata.json with loading order
Example:
```
{"AssemblyLoadingOrder":["SubSubProject","SubProject2","SubProject","Core"]}
```
3. U# plugin read this info and load assembly with their metadata in correct order.
Example:
1. TestController:
3. TestComponent:
Result:
I'm not sure of the correct implementation, but in my tests everything work fine.

U# project referencing

---

Source/UnrealSharpCore/CSDeveloperSettings.h
Source/UnrealSharpEditor/CSCommands.cpp
Source/UnrealSharpEditor/CSCommands.h
Source/UnrealSharpEditor/UnrealSharpEditor.cpp
Source/UnrealSharpEditor/UnrealSharpEditor.h

I added a quick functionality that let's users build the modules in their IDEs and then let UnrealSharp only weave and reload the modules instead of building them. This allows me to handle any errors of my code inside my IDE and let UnrealSharp only do the reload work when it's actually needed.
I also added two shortcuts so compiling & reloading can be accessed quickly.
If that change is ok I would also go ahead and implement automatic reloading if the module files changed to complete this additional workflow.

Add functionality to reload modules only & Add shortcuts

---

Source/UnrealSharpEditor/Reinstancing/CSReinstancer.cpp

-additional missing reinstancing code to support hot reload using u# types
-fix map, array, and set types
-fix interface function overloads which work with func refs:

Adding more re instancing code for known collection types (map, array or set)

---

Managed/UnrealSharpPrograms/UnrealSharpBuildTool/BuildToolProcess.cs
Source/UnrealSharpProcHelper/CSProcHelper.cpp

this is when the weaver will run into errors. this is then deadlocking unreal during c# compilation.
also give UE thread a little rest time while waiting for recompilation process output

[BUG, DEADLOCK] fix build tool may deadlock on reading weaver output and error streams in sequence

---

Source/UnrealSharpCore/UnrealSharpCore.Build.cs

Fixed issue causing C# C4429 warning due to folder names starting with a lowercase 'u' in the directory

Fixed issue causing C# C4429 warning due to folder names starting with a lowercase 'u' in the directory

---

Managed/UnrealSharp/UnrealSharp/Extensions/CoreUObject/Object.cs
Managed/UnrealSharp/UnrealSharp/Extensions/Engine/AssetManager.cs
Managed/UnrealSharp/UnrealSharp/Marshallers.cs
Source/UnrealSharpCore/Export/FCSManagerExporter.cpp
Source/UnrealSharpScriptGenerator/Exporters/FunctionExporter.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/ObjectPropertyTranslator.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/PropertyTranslator.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/PropertyTranslatorManager.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/WorldContextObjectPropertyTranslator.cs

Removed the need for WorldContextObject (usually you had to type "this") when calling certain static functions, now it automatically defaults to the current world object instead
Before:
```
SystemLibrary.LineTraceByChannel(this, start, end, traceChannel, false, new List<AActor>(), EDrawDebugTrace.None, out FHitResult hit, true);
```
Now:
```
SystemLibrary.LineTraceByChannel(start, end, traceChannel, false, new List<AActor>(), EDrawDebugTrace.None, out FHitResult hit, true);
```

Remove world context object

---

Managed/UnrealSharp/UnrealSharp/Interop/AsyncExporter.cs
Managed/UnrealSharp/UnrealSharp/UnrealSynchronizationContext.cs
Source/UnrealSharpCore/Export/AsyncExporter.cpp
Source/UnrealSharpCore/Export/AsyncExporter.h

Async delegates do not have WorldContext set causing errors for anything that requires it, this PR fixes that.

Fixes WorldContext not being set during Async

---

Source/UnrealSharpScriptGenerator/Utilities/PropertyUtilities.cs

This PR fixes an issue where certain properties were not correctly getting the highest getter and setter access modifier, causing the property to become protected when it should be public.

Fixes certain property access modifiers

---

Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/BuildWeave.cs
Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/GenerateProject.cs
Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/WeaveProject.cs
Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Program.cs

When managing a project with Git, it is necessary to ignore the Properties/launchSettings.json file in all .NET projects within the Script folder because this file stores the absolute paths of Unreal Engine and the project on the local machine. However, the Properties/launchSettings.json file is only generated when a C# project is initially created. Therefore, a mechanism is needed to detect all .NET projects in the Script folder (excluding ProjectGlue) upon each project startup and automatically add the Properties/launchSettings.json file to the ignore list.

Check for missing launchSettings.json in C# project files during UE startup and add it if absent.

---

Managed/UnrealSharp/UnrealSharp/UnrealSynchronizationContext.cs

For multi session/world context running under the same process the previous fix for async world context caused issues, this fixes that by removing cache for now and getting the world context on construct.

Fixes async multi world/session WorldContext issues

---

Managed/UnrealSharp/UnrealSharp/Extensions/Engine/Actor.cs
Source/UnrealSharpScriptGenerator/Exporters/FunctionExporter.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/BlittableTypePropertyTranslator.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/ClassPropertyTranslator.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/ContainerPropertyTranslator.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/DelegateBasePropertyTranslator.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/InterfacePropertyTranslator.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/MapPropertyTranslator.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/ObjectPropertyTranslator.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/PropertyTranslator.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/SimpleTypePropertyTranslator.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/SoftClassPropertyTranslator.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/SoftObjectPropertyTranslator.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/StringPropertyTranslator.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/StructPropertyTranslator.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/TextPropertyTranslator.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/WeakObjectPropertyTranslator.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/WorldContextObjectPropertyTranslator.cs
Source/UnrealSharpScriptGenerator/Utilities/FunctionUtilities.cs
Source/UnrealSharpScriptGenerator/Utilities/PropertyUtilities.cs

This PR is to support a feature of automatic generic generation in UFunctions using the DeterminesOutputType and DynamicOutputParam MetaData that Uht has on UFunctions.
Example of Generic Source Gen:
```CSharp
public static void GetAllActorsOfClass<DOT>(out System.Collections.Generic.IList<DOT> outActors) where DOT : UnrealSharp.Engine.AActor
{
GetAllActorsOfClass<DOT>(typeof(DOT), out outActors);
}
/// <summary>
/// Find all Actors in the world of the specified class.
/// This is a slow operation, use with caution e.g. do not use every frame.
/// 
/// </summary>
[UFunction, GeneratedType("GetAllActorsOfClass"), UMetaData("DeterminesOutputType", "ActorClass"), UMetaData("DynamicOutputParam", "OutActors")]
public static void GetAllActorsOfClass<DOT>(TSubclassOf<DOT> actorClass, out …
```

Support for DeterminesOutputType automatic generics generation in UFunctions

---

Managed/UnrealSharp/UnrealSharp/Extensions/CoreUObject/Object.cs

This pr allows for implicit boolean operations on UObjects so you can check if they valid as a bool in an if statement similar to how you can in Unreal.

Implicit boolean operator for UObjects

---

Managed/UnrealSharp/UnrealSharp/Interop/UFunctionExporter.cs
Managed/UnrealSharp/UnrealSharp/MarshalledStruct.cs
Managed/UnrealSharp/UnrealSharp/Marshallers.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/WeaverHelper.cs
Source/UnrealSharpCore/Export/UFunctionExporter.cpp
Source/UnrealSharpCore/Export/UFunctionExporter.h
Source/UnrealSharpCore/Export/UObjectExporter.cpp
Source/UnrealSharpCore/Export/UScriptStructExporter.cpp
Source/UnrealSharpCore/Export/UScriptStructExporter.h
Source/UnrealSharpScriptGenerator/Exporters/FunctionExporter.cs
Source/UnrealSharpScriptGenerator/Exporters/StructExporter.cs
Source/UnrealSharpScriptGenerator/GeneratorStringBuilder.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/IntPropertyTranslator.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/PropertyTranslator.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/PropertyTranslatorManager.cs
Source/UnrealSharpScriptGenerator/PropertyTranslators/StructPropertyTranslator.cs
Source/UnrealSharpScriptGenerator/Utilities/FunctionUtilities.cs
Source/UnrealSharpScriptGenerator/Utilities/PropertyUtilities.cs
Source/UnrealSharpScriptGenerator/Utilities/StaticConstructorUtilities.cs

This PR moderately reworks struct and function exporting to allow for `UFunction`s with the `CustomStructureParam` metadata specifier to be exported as generic functions. This is accomplished with the following changes:
- Creates an interface `MarshalledStruct<T> where T: MarshalledStruct<T>`, containing several abstract static and member methods for generically getting the native `UScriptStruct` pointer and the native struct size, along with translating the structs to/from native buffers.
- Changes the script generator to automatically implement `MarshalledStruct` for all exported `UStruct`s, including manually exported blittable structs.
- If requested, the automatically generated implementations can be manually copied to the manually exported types, and the code to generate the …

`UFunction`s with `CustomStructureParam`s are exported and invoked as generic c# functions

---

.gitignore
Source/UnrealSharpScriptGenerator/UnrealSharpScriptGenerator.ubtplugin.csproj.props

This PR removes UnrealSharpScriptGenerator props file as it gets autogen when generating project files.
fixes #351

Removed autogen .props files and added them to gitignore

---

Source/UnrealSharpScriptGenerator/Utilities/ScriptGeneratorUtilities.cs

- Fix AutocastExporter use wrong managed name in generated class.  Example see original issue https://github.com/UnrealSharp/UnrealSharp/pull/362
- Fix interface function exported twice if it is identified as a property getter or setter.
Example:
```c++
class MYGAME_API IMyInterface
{
GENERATED_IINTERFACE_BODY()
UFUNCTION()
virtual WeaponObj* GetWeapon();
}
class MYGAME_API AMyActor: public IMyInterface
{
GENERATED_UCLASS_BODY()
UPROPERTY()
WeaponObj* Weapon;
UFUNCTION()
virtual WeaponObj* GetWeapon() override
{
return Weapon;
}
}
```
> P.S. It can be fixed by removing `UFUNCTION()` in the implementation class. But it is unnatural and generator can solve it more elegantly.

Fix ScriptGeneratorUtilities.GetExportedFunctions bug

---

Managed/UnrealSharp/UnrealSharp/Extensions/CoreUObject/Object.cs

This issue fixes an engine execution error due to using the wrong method for calling into a function pointer.

Fixes issue with widget create using wrong method

---

Source/UnrealSharpCore/TypeGenerator/Register/CSGeneratedClassBuilder.cpp

This issue fixes default tick settings not being reapplied to the new CDO after a hot reload.
Fixes #383

Fixes an issue with default tick settings not reapplying after hotreload

---

Managed/UnrealSharpPrograms/UnrealSharpWeaver/Program.cs
Source/UnrealSharpProcHelper/CSProcHelper.cpp

This PR fixes some json errors when parsing UnrealSharp.metadata.json. Since the metadata is a different kinda of data structure it fails to get the normal fields in a user assembly.

Fixes issues with loading UnrealSharp.metadata.json

---

Managed/UnrealSharp/UnrealSharp/Interop/UScriptStructExporter.cs
Source/UnrealSharpCore/Export/UScriptStructExporter.cpp
Source/UnrealSharpCore/Export/UScriptStructExporter.h
Source/UnrealSharpManagedGlue/CSharpExporter.cs
Source/UnrealSharpManagedGlue/Exporters/StructExporter.cs
Source/UnrealSharpManagedGlue/PropertyTranslators/PropertyTranslatorManager.cs
Source/UnrealSharpManagedGlue/Utilities/StructUtilities.cs

`FMoverDataCollection` is a non-POD data type due to it having virtual methods (at least `StaticStruct`). However, it can be copied using `CppStructOps::Copy`, and has to be, due to possessing a non-reflected member property that is relevant for reflection-exposed functions. This PR adds support for marshalling structs by performing a native cpp struct ops copy, and adds that support to `FMoverDataCollection`.

Adds support for marshalling structs using `CppStructOps::Copy`, exports `FMoverDataCollection` using this functionality

---

Source/UnrealSharpCore/TypeGenerator/Factories/CSFunctionFactory.cpp
Source/UnrealSharpCore/TypeGenerator/Functions/CSFunction_Params.cpp

`CSFunctionFactory::CreateOverriddenFunction` did not apply the `HasOutParms` function flag to overrides of functions that do.
This prevented `UObject::ProcessEvent` from creating an output property chain when invoking such functions. This is relevant for c# implementations of UInterface functions, as `ProcessEvent` is part of the code path used to execute non-native implementations of said functions.
Additionally, `CSFunction_Params::InvokeManagedMethod_Params` uses the output property chain of the passed in function (if present) when the function is being called from native code. This allows native invocations to correctly receive the output params of the c# function.

Natively-called c# Overrides Properly Copy Output Params

---

Managed/UnrealSharp/UnrealSharp.Editor/UnrealSharp.Editor.csproj

This PR updates old version of Microsoft build tools being used instead of recent up-to-date version causing an issue with other nuget package.

Updated UnrealSharp.Editor build tool nuget version

---

Managed/UnrealSharp/UnrealSharp/Extensions/EnhancedInput/EnhancedInputComponent.cs
Managed/UnrealSharp/UnrealSharp/Interop/UEnhancedInputComponentExporter.cs
Source/UnrealSharpCore/Export/UEnhancedInputComponentExporter.cpp
Source/UnrealSharpCore/Export/UEnhancedInputComponentExporter.h

This PR allows input actions to be unbound after binding them. To do this, `UEnhancedInputComponent.BindAction` now has an `out uint` parameter that returns the binding's unique handle. The old signature is now an overload that discards the handle parameter. You can pass the output handle to `UEnhancedInputComponent.UnbindAction` to unbind the Action from the Input Action. Both `BindAction` and `UnbindAction` now return `bool`, specifying whether their respective operations were successful.

Input Actions can be unbound from c#

---

Source/UnrealSharpCore/Export/UObjectExporter.cpp

This PR fixes an issue where network functions with local callspace are getting ignored instead of getting called, this is not an expected behaviour and the local function should still get called.

Fixes local callspace calls on networked functions

---

Source/UnrealSharpCore/Export/UScriptStructExporter.cpp

This PR adds a fallback memcpy if the CppStructOps doesn't have the capability of copying.

Added memcpy fallback for NativeCopy

---

Managed/UnrealSharp/UnrealSharp/Extensions/Engine/AssetManager.cs

`if (loaded is not T typedObject)
{
throw new InvalidCastException($"Asset '{assetId}' could not be cast to '{typeof(T).Name}' or was not found.");
}
`
this caused editor crash when use AssetManager to load Blueprint. 
Instead, `SystemLibrary.GetClass` should be used to load the class, and compare to `typeof<T>`

Fixed LoadPrimaryAssetClass

---

Source/UnrealSharpCore/TypeGenerator/Functions/CSFunction_Params.cpp

Fixed an issue where the location of the local variables in the stack frame is changed and not restored before the call ends, leading to stack corruption when making additional calls.

Fixed stack frame corruption when calling to C# from Blueprints

---

Config/Default.UnrealSharpTypes.json
Managed/UnrealSharp/UnrealSharp.Core/Marshallers/BlittableMarshaller.cs
Managed/UnrealSharp/UnrealSharp.Core/Marshallers/MarshalledStruct.cs
Managed/UnrealSharp/UnrealSharp/Extensions/CoreUObject/Object.cs
Managed/UnrealSharp/UnrealSharp/Extensions/UnrealSharp/SubsystemCollectionBaseRef.cs
Managed/UnrealSharp/UnrealSharp/Interop/FSubsystemCollectionBaseRefExporter.cs
Source/UnrealSharpCore/Export/FSubsystemCollectionBaseRefExporter.cpp
Source/UnrealSharpCore/Export/FSubsystemCollectionBaseRefExporter.h
Source/UnrealSharpCore/Extensions/Subsystems/CSEngineSubsystem.h
Source/UnrealSharpCore/Extensions/Subsystems/CSGameInstanceSubsystem.h
Source/UnrealSharpCore/Extensions/Subsystems/CSLocalPlayerSubsystem.h
Source/UnrealSharpCore/Extensions/Subsystems/CSWorldSubsystem.cpp
Source/UnrealSharpCore/Extensions/Subsystems/CSWorldSubsystem.h
Source/UnrealSharpCore/Extensions/Subsystems/SubsystemCollectionBaseRef.h
Source/UnrealSharpEditor/UnrealSharpEditor.Build.cs
Source/UnrealSharpRuntimeGlue/UnrealSharpRuntimeGlue.Build.cs

In C++ subystems are able to declare dependencies through the `InitializeDependency` method on `FSubsystemCollectionBase`, however since this type is not exposed to Blueprints there is no way to handle this same thing in C#. To rectify this, I created `FSubsystemCollectionBaseRef` as a wrapper struct that holds a pointer to the underlying `FSubsystemCollectionBase` object. This is then reflected in C# by the type having a single property of type IntPtr and being marked as Blittable. The struct is also defined as a readonly ref struct to ensure that it cannot escape the context of the initialize method that called it. Additional support code was also modified to add `allows ref struct` so that this struct can be defined this way. 
The struct has two distinct method overload sets. …

Updated subsystems so there is a way to request dependencies in C#

---

Managed/UnrealSharp/UnrealSharp/Extensions/Engine/AssetManager.cs
Source/UnrealSharpManagedGlue/PropertyTranslators/SoftClassPropertyTranslator.cs

`softClassProperty.Class.GetFullManagedName()` translated T as UClass, which is supposed to be an UObject.

Fixed TSoftClassPtr<T>

---

Source/UnrealSharpManagedGlue/PropertyTranslators/PropertyTranslatorManager.cs

This fixed an issue that was reported where having plugins in the project without a Config directory the project could not be built.

Fixed an issue where if a project plugin lacked a config directory the UHT would crash

---

Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Program.cs
Source/UnrealSharpProcHelper/CSProcHelper.cpp
Source/UnrealSharpProcHelper/CSProcHelper.h
Source/UnrealSharpProcHelper/UnrealSharpProcHelper.Build.cs

Currently, if the project encounters an analyzer during the initial build or during hot reload of the plugin will display an error. This fixes it by ensuring any .csproj files in the project that have `IsRoslynComponent` set to `true` are ignored by the weaver and hot reloader as they are build-only artifacts.

Allow users to define analyzers in their project code

---

Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/BuildWeave.cs
Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/GenerateProject.cs
Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/UpdateProjectDependencies.cs
Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Program.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/NativeTypes/NativeDataSimpleType.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/Program.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/Utilities/AssemblyUtilities.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/WeaverImporter.cs
Source/UnrealSharpEditor/Plugins/CSPluginTemplateDescription.cpp
Source/UnrealSharpEditor/Plugins/CSPluginTemplateDescription.h
Source/UnrealSharpEditor/Slate/CSNewProjectWizard.cpp
Source/UnrealSharpEditor/UnrealSharpEditor.cpp
Source/UnrealSharpManagedGlue/CSharpExporter.cs
Source/UnrealSharpManagedGlue/Program.cs
Source/UnrealSharpManagedGlue/Properties/launchSettings.json
Source/UnrealSharpManagedGlue/Utilities/FileExporter.cs
Source/UnrealSharpManagedGlue/Utilities/PackageUtilities.cs
Source/UnrealSharpManagedGlue/Utilities/PluginUtilities.cs
Source/UnrealSharpProcHelper/CSProcHelper.cpp

All glue projects are just now called `PluginName/ProjectName.Glue.csproj` instead of `.PluginGlue.csproj` for plugins and `ProjectGlue.csproj` for the project's glue
References to old `ProjectGlue.csproj` can be removed and instead reference `ProjectName.Glue.csproj`. This project will only appear if you have any C++ code in your game project.

Project Glue Rework

---

Managed/UnrealSharp/UnrealSharp.Binds/BindsManager.cs
Managed/UnrealSharp/UnrealSharp.Core/ManagedCallbacks.cs
Managed/UnrealSharp/UnrealSharp.Core/UnmanagedCallbacks.cs
Managed/UnrealSharp/UnrealSharp/Interop/ExportedFunctionsManager.cs
Managed/UnrealSharpPrograms/UnrealSharpBuildTool/Actions/PackageProject.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/NativeTypes/NativeDataContainerType.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/TypeProcessors/PropertyProcessor.cs
Managed/global.json
Source/UnrealSharpCore/CSAssembly.cpp
Source/UnrealSharpCore/CSManagedCallbacksCache.h
Source/UnrealSharpUtilities/UnrealSharpUtils.cpp

- Add the exception message and stacktrace to the log when the managed counterpart was failed to create to improve the diagnosability when an exception was thrown from the constructor
- Replace `Marshal.GetDelegateForFunctionPointer` and `Marshal.GetFunctionPointerForDelegate` with function pointers to reduce the overhead
- Properly generates the setter, and skip the initialization for `ldnull` to avoid marshalling a null value for types like `TArray` and etc. A field with reference type should already have `null` as the initial value by default (a follow up to #512)
- Tweak the global.json to allow using a prerelease version of .NET SDK
- Only purge metadata when it's available to avoid build errors during packaging with Shipping configuration
- Override the `OutputPath` to use the …

Various fixes and improvements

---

Managed/UnrealSharp/UnrealSharp/MulticastDelegate.cs

The order of argument `NativeProperty` and `NativeDelegate` was wrong...

Fix MulticastDelegate.Clear not working

---

Managed/UnrealSharpPrograms/UnrealSharpWeaver/TypeProcessors/FunctionProcessor.cs

When I mark a function parameter as 'ref' in c#, and use blueprint or C++ to call this function, the parameter will be marked as PropertyFlags.OutParm and PropertyFlags.ReferenceParm together.
The according to the PropertyFlags.OutParm, the value of parameter can't be got.

Fix : Can't get value of function parameter which is ReferenceParam.

---

Directory.Packages.props

I accidently made a typo where the version of `Microsoft.CSharp` should be 4.7.0, instead of 4.13.0.
Also move `Directory.Package.props` to the parent directory so that it also applies to projects under `Source.`

Fix package version

---

Source/UnrealSharpManagedGlue/Program.cs

The current way of locating project directories assumes that plugins are placed in the Plugins directory. 
However, developers may need to further organize plugins using subdirectories. 
This PR changes the way project directories are located, looking upwards to the Plugins directory to support placing plugins in subdirectories.Refactor directory traversal logic to locate project root from plugin path.

Refactor directory traversal logic to locate project root from plugin path

---

Source/UnrealSharpManagedGlue/Program.cs
Source/UnrealSharpManagedGlue/Utilities/FileExporter.cs
Source/UnrealSharpManagedGlue/Utilities/PluginUtilities.cs

This PR is a fairly straightforward. It allows for users to extract specific engine modules out into their own plugins for glue generation. This might come in handy for extending plugins that are not enabled by default (i.e. GAS). This will also help users who need to integrate with FAB plugins as well.

Added logic to allow an engine modules to be extracted out info a plugin

---

Managed/UnrealSharp/UnrealSharp/MapBase.cs
Managed/UnrealSharpPrograms/UnrealSharpWeaver/NativeTypes/NativeDataContainerType.cs

Collection members in structs should be marshalled using copy-semantics, as the C# representation of collections are reference types and so may live on past the scope of the uproperty that holds the struct. The glue generator gets this right, however the weaver does not. This fixes the weaver to use copy marshallers for structs.
Example:
```CSharp
[UStruct]
public struct FMyMap
{
[UProperty]
public IDictionary<int, int> Map;
}
...
// In some UClass
[UProperty]
public FMyMap MyMap { get; set; }
...
MyMap = new() { Map = new Dictionary<int, int>() { { 1, 2 } } };
MyMap = new() { Map = new Dictionary<int, int>() { { 2, 3 } } };
// MyMap should contain only [2, 3] but instead contains both [1, 2] and [2, 3]
```
Also, marshalling a map into a uproperty was not clearing the underlying map, …

Fix C#-defined structs not using copy marshallers for collections

---

Source/UnrealSharpManagedGlue/Exporters/GetterSetterFunctionExporter.cs
Source/UnrealSharpManagedGlue/Utilities/ScriptGeneratorUtilities.cs

- Property pairing was dependent on accessor discovery order. When the setter was encountered first, the property type came from the setter parameter, and the getter wrapper omitted a return if the return type differed — generating invalid code (empty getter).
- Prefer the getter’s value type (return or out) as the canonical property type and bind both getter and setter exporters to it. Always emit a return in getter wrappers (implicit conversions handle mismatches like FText->string).
Fix for #459

Fix generation for cases where property getter & setter differ in their types.
